### ISSUE TITLE
v2rayp crashed when using Core 3.10

### ISSUE THREAD

**Issue by yanjing-sisu** [PoseidonM4A4/v2rayP#3]
Version 3.9 didn't have so bug. Thx

**Comment by ustczzh** [comment]
Same problem, fall back to Version 3.9 for now!

**Comment by PoseidonM4A4** [comment]
currently work on it @yanjing-sisu @ustczzh

**Comment by PoseidonM4A4** [comment]
Issue settled.

See [[2c7b9844]](https://github.com/PoseidonM4A4/v2rayP/commit/2c7b9844534152140b67250f80a27beb12f503c5)

I use a regular expression to extract v2ray core version number by executing ``v2ray.exe -version`` and capture the stdout.

stdout:
normal  ``` V2Ray v3.12 (die Commanderin) 20180306```
v3.10      ```V2Ray v3.10(die Commanderin)20180222```

Attention: There is no space after v3.10
